name: skin_sense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.4.3

dependencies:
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_native_image: ^0.0.6
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  image_cropper: ^8.0.2
  intl: ^0.19.0
  logger: ^2.4.0
  tflite_v2: ^1.0.0
  hive: ^2.2.3
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.1.2
  google_ml_vision: ^0.0.8
  animated_segmented_tab_control: ^2.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: 2.4.11
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/model/
    - assets/images/
  
