// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5hor62RJgQrSvNRSR8Xe0CdJ4vIUNBSk',
    appId: '1:575729018242:web:c5db16e9afed4ccea99b9b',
    messagingSenderId: '575729018242',
    projectId: 'skin-sense-dfb1b',
    authDomain: 'skin-sense-dfb1b.firebaseapp.com',
    storageBucket: 'skin-sense-dfb1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoU-sxjhXEvGT8T6toaVTqQkcNQc5ET9o',
    appId: '1:575729018242:android:5910f30fa37a030ea99b9b',
    messagingSenderId: '575729018242',
    projectId: 'skin-sense-dfb1b',
    storageBucket: 'skin-sense-dfb1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6cnXTUS0amQeWk1BxpPk-iuk0A-AJSQ',
    appId: '1:575729018242:ios:e698feedf8153101a99b9b',
    messagingSenderId: '575729018242',
    projectId: 'skin-sense-dfb1b',
    storageBucket: 'skin-sense-dfb1b.appspot.com',
    iosBundleId: 'com.example.skinSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6cnXTUS0amQeWk1BxpPk-iuk0A-AJSQ',
    appId: '1:575729018242:ios:e698feedf8153101a99b9b',
    messagingSenderId: '575729018242',
    projectId: 'skin-sense-dfb1b',
    storageBucket: 'skin-sense-dfb1b.appspot.com',
    iosBundleId: 'com.example.skinSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5hor62RJgQrSvNRSR8Xe0CdJ4vIUNBSk',
    appId: '1:575729018242:web:d2132a60a5e8d49da99b9b',
    messagingSenderId: '575729018242',
    projectId: 'skin-sense-dfb1b',
    authDomain: 'skin-sense-dfb1b.firebaseapp.com',
    storageBucket: 'skin-sense-dfb1b.appspot.com',
  );

}